### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by ddelange** [Melevir/flake8-cognitive-complexity#4]
Hi!

We're looking to use your plugin, but I noticed this repo is not fully licensed (only MIT marker in setup.py) as opposed to https://github.com/best-doctor/flake8-expression-complexity.

Could you add the MIT license to this repo and make a new release?

Thanks in advance,

David

**Comment by Melevir** [comment]
Thanks for the report. Done in 0.1.0.

**Comment by ddelange** [comment]
Thanks for the quick response! 💥
